### ISSUE TITLE
[BUG] - False linking of HD assets to their SD counterparts on duplicates with differing names.

### ISSUE THREAD

**Issue by TopazTK** [Xeeynamo/OpenKh#571]
**OpenKH Build**
Build: [20220225.3](https://github.com/Xeeynamo/OpenKh/releases/tag/release-377)

**OpenKH Program**
OpenKH.Command.IdxImg

**Describe the Bug**
Two subjects:
- P_EX020.a.us - Exists in the game.
- P_EX020.a.jp - Does NOT exist in the game.

When the former is patched, the program finds 7 HD assets to link, so all is dandy.
However, when the latter is patched in, the program finds 8 SD assets to link to the HD assets, which there are only 7.
This causes the HD assets to get linked in an incorrect matter, shifting all of the effects used: breaking them.

**To Reproduce**

_I have given a **.a.jp** file as an example in the report, but I will give a **NEW.a.us** file to reproduce this, since previewing **.a.jp** files are a pain._

1. Extract **P_EX020.a.us** from **kh2_sixth**
2. Patch **P_EX020.a.us** as **P_EX020_NEW.a.us** (And all the co-files that go along with it. Like the MSET and the MDLX)
3. Preview the file by changing **P_EX020** to **P_EX020_NEW** in the **00objentry.bin** (Preferably from RAM)
4. Observe.

**Expected behavior**
The files act 1:1 to one another. No messiness, no tricks, no compromises.

**Screenshots**
![image](https://user-images.githubusercontent.com/95656963/155760346-4242d8d6-47e2-4113-a71f-cfceb7ebac2b.png)
![image](https://user-images.githubusercontent.com/95656963/155760381-10e555c5-4013-4223-ac80-44fdf2d352fc.png)
![image](https://user-images.githubusercontent.com/95656963/155760395-67edc6fa-7e32-430e-8c66-7a55f1206ce7.png)

**Additional context**
With the context of all **.a.us** files copied and patched in as **.a.jp**, and the game modified to seek the latter instead of the former, the following are true:

Screenshot 1: P_EX020.a.jp reports 8 SD files found. This should be 7.
Screenshot 2: Save Point assets are out of order and so it appears broken. Donald's face is still SD.
Screenshot 3: All in battle PAX are out of order, so it appears buggy.

**Comment by TopazTK** [comment]
I can think of 3 ways to fix this issue:
- Allow extracting/patching with unstripped files for maximum compatibility.
- Provide the option to patch in with a SHIM, so that the author can ensure HD gets linked to HD, not SD
- Just, create a SHIM according to the HD folder and not the SD file, though this may cause issues.

**Comment by TopazTK** [comment]
Fixed with #572.
Not closing as tiny traces of the issue still persist.

**Comment by Vladabdf** [comment]
Could you give details on which issues persist?

**Comment by TopazTK** [comment]
On some PAX, the assets still get messed up.
Examples are Ultima Weapon's Hit Stars, Hollow Bastion's Drones, Vexen's Icicles (But only the ground effect of it), etc.

**Comment by o0DemonBoy0o** [comment]
I assume this is when importing a new a.jp file with the remastered asset order of a matching a.us file?

**Comment by TopazTK** [comment]
Exactly.

**Comment by o0DemonBoy0o** [comment]
Then yeah I'm unsure if there is a correct way of dealing with that issue.
As mentioned in the comments of the PAX code and in #572 there doesn't appear to be any real way to tell how the devs linked the remastered assets to the original files for PAX textures. I can correctly get every offset for linking, but I can't reliably link them in the same order as the devs did. There unfortunately just doesn't seem to be any real pattern or order that I can see after going through multiple files. I can only assume this was something done manually rather than automatically atthis point.

**Comment by TopazTK** [comment]
A secondary fallback option would be to extract the SHIMs and let them be edited separately. Maybe that would be possible?

**Comment by o0DemonBoy0o** [comment]
Is there need for a fallback though? 
The offsets are gotten correctly, just the process or ordering them isn't the same as how the devs did it when they packaged the game.
The scenario you have here seems extremely specific to what you are trying to do because you are trying to use the same order of an existing file for one you are importing as brand new to the game. Any other modder importing a brand new PAX for their mod would just order their custom HD assets as they appear in the SD asset and be done with it. no need to think of how the devs would have ordered the textures because it doesn't matter.

**Comment by TopazTK** [comment]
Yea, fair point, but nice to have fallbacks, you know.
What if someone ELSE tried something as dumb as I have?

**Comment by TopazTK** [comment]
Regardless, let's take this particular conversation out of this issue.

**Comment by Vladabdf** [comment]
> Yea, fair point, but nice to have fallbacks, you know. What if someone ELSE tried something as dumb as I have?

If an issue like this arises because of user choice and can be prevented given the linked fix + suggestion (with the help of condole output to guide or otherwise assist the user), then that is honestly good enough for me. As long as everything works and there is a workflow to be followed where the issue doesn't occur, then the process should be considered functional. Agreed? 🙂

**Comment by Delta-473** [comment]
The best way maybe is to print it when it creates a new file (a warning in yellow text color), idk if there are better ways to detect if it goes wrong
