### ISSUE TITLE
Petition: Change Structure of OpenKh.Tools.* and OpenKh.Command.* Folders

### ISSUE THREAD

**Issue by Vladabdf** [Xeeynamo/OpenKh#68]
The current folder structure works for now, but with how many tools there are going to be, and seeing how many tools may end up being game-specific (or in the case of BbS and DDD, engine-specific), the project is going to reach a point where the root folder will have far too many sub-folders to navigate. I suggest restructuring the entire project's folder heirarchy to be something along the lines of the provided image (but not exactly the same of course) so navigation/finding a specific folder will be less arduous in the future. Of course this would entail changing some folder names entirely, but I feel as though it would help with organization in the long run. Thoughts?

![folder structure suggestion](https://user-images.githubusercontent.com/20749232/72676885-11eb5f00-3a64-11ea-9b7f-81f007b5158b.png)

**Comment by Xeeynamo** [comment]
Makes sense. The thing that refrains me to do so is because you are supposed to navigate through the folders using the solution file and that I chosen to have prefix on tool names just to avoid the evenience to have sub-folders. I am still thinking if the current structure is the right approach and what are the implications to change it.

**Comment by Vladabdf** [comment]
That's a fair point, though to my knowledge (and I could be very wrong about this, so please correct me if so), Linux and Mac users who may wish to contribute cannot use solution files. Your reasoning makes sense from a Windows perspective if that is indeed the case.
